# ===============================
# ? ENVIRONMENT CONFIGURATION
# ===============================
env=qa

base.url.dev=https://dev.saucedemo.com
base.url.qa=https://www.saucedemo.com
base.url.prod=https://www.saucedemo.com

#===============================
base.api.url=https://reqres.in/api

# ===============================
# EXECUTION CONFIGURATION
# ===============================
parallel.execution=true
thread.count=8

# ===============================
# ? BROWSER CONFIGURATION
# ===============================
#browser=chrome
browser=firefox
headless=true
windowMaximize=false

# Supported: chrome, firefox, edge
# Override via CLI:
# mvn test -Dbrowser=firefox -Dheadless=false

# ===============================
# ? TIMEOUTS
# ===============================
implicitlyWait=2
# future-ready:
explicitWait=10
pageLoadTimeout=30

# ===============================
# ? SCREENSHOT CONFIGURATION
# ===============================
takeScreenShot=true
screenShotsPath=target/test-output/screenshots/

# ===============================
# ? DRIVER CONFIGURATION
# ===============================
driverPath=src/main/resources/drivers/

# ===============================
# ? EXECUTION METADATA (for Allure / Reporting)
# ===============================
tester=Vadim Pasat
project.name=AutomationPractice_01
execution.type=local

# ===============================
# ? OPTIONAL (CI/CD READY)
# ===============================
build.number=local-run
pipeline.name=local