#Project Properties
base.url.dev=https://dev.saucedemo.com
base.url.qa=https://www.saucedemo.com
base.url.prod=https://www.saucedemo.com
env=qa
#browser=firefox
browser=chrome
driverPath=src/main/resources/drivers/
windowMaximize=true
implicitlyWait=2
screenShotsPath=target/test-output/screenshots/
takeScreenShot=true
headless=true
